name: Deploy Branch Preview
on:
  pull_request:

jobs:
  deploy_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: Preview
      firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_USHS_HOUSING_PORTAL_STAGING }}"
      firebaseProjectId: ushs-housing-portal-staging
    secrets: inherit
