name: Deploy Branch Preview
on:
  pull_request:

jobs:
  build_and_preview:
    name: Build and Deploy
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Build Frontend
        run: |
          cd frontend
          bun install --frozen-lockfile
          bun run build
      - name: Build Backend
        run: |
          cd backend
          bun install --frozen-lockfile
          bun run build
      - name: Create Backend .env
        run: |
          cd backend
          touch .env
          echo NODE_ENV=${{ vars.NODE_ENV }} >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          echo FRONTEND_ORIGIN=${{ vars.FRONTEND_ORIGIN }} >> .env
      - name: Deploy Branch to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_USHS_HOUSING_PORTAL_STAGING }}"
          projectId: ushs-housing-portal-staging
        env:
          FIREBASE_CLI_EXPERIMENTS: pintags
